### ISSUE TITLE
Duplicate policies when running terraform apply

### ISSUE THREAD

**Issue by GERey** [dgkirkwood/teleport-terraform-quickstart#1]
The terraform apply command tries to create IAM Policy proxy-ec2describe and IAM role proxy-ec2_assume. Even though they already exist. Either we should make the above names dynamic or have a check to see if those policies already exist and skip.  

pasted the error below. 

Error: error creating IAM Policy proxy-ec2decribe: EntityAlreadyExists: A policy called proxy-ec2decribe already exists. Duplicate names are not allowed.
│ 	status code: 409, request id: 0fe75764-6373-4999-b8cb-7ae7a56421bf
│ 
│   with aws_iam_policy.describeinstances,
│   on iam.tf line 1, in resource "aws_iam_policy" "describeinstances":
│    1: resource "aws_iam_policy" "describeinstances" {
│ 
╵
╷
│ Error: failed creating IAM Role (proxy-ec2_assume): EntityAlreadyExists: Role with name proxy-ec2_assume already exists.
│ 	status code: 409, request id: 71680695-d96f-43ed-b674-5e3466fb1186
│ 
│   with aws_iam_role.ec2_assume,
│   on iam.tf line 26, in resource "aws_iam_role" "ec2_assume":
│   26: resource "aws_iam_role" "ec2_assume" {

**Comment by GERey** [comment]
action item out of this is to attach prefixes since you should be destroying anyways at the end of it.

**Comment by dgkirkwood** [comment]
Added prefix as a variable and prepended the IAM policy names with this prefix to reduce the chance of a resource name collision. Commit - https://github.com/dgkirkwood/teleport-terraform-quickstart/commit/ae7643d4b98395dcfdeadba562f75f7111b4a1b4
