### ISSUE TITLE
variables.auto.pkvars.hcl isn't registered for variables.pkr.hcl

### ISSUE THREAD

**Issue by GERey** [dgkirkwood/teleport-terraform-quickstart#2]
Using packer version 1.8.3 it doesn't seem to respect variables.auto and only takes defaults if they're in the varaibles.pkr.hcl file itself.

**Comment by dgkirkwood** [comment]
OK so I was doing some troubleshooting here and and worked out the problem... it is my dodgy readme! The readme says you need a file `variables.auto.pkvars.hcl` whereas it should be called `variables.auto.pkrvars.hcl`. 

This is why it was not being picked up 🤦‍♂️

I will edit the README and close this issue as my testing with `variables.auto.pkrvars.hcl` works without issue, but if you can test and confirm that would be great!
