### ISSUE TITLE
InvalidKeyPair.NotFound: The key pair 'dk-rsa' does not exist

### ISSUE THREAD

**Issue by GERey** [dgkirkwood/teleport-terraform-quickstart#3]
Is it using the key we provide it? It seems like the key pair dk-rsa is hardcoded ...which is cool if your DK but I'm not :)

**Comment by GERey** [comment]
https://github.com/dgkirkwood/teleport-terraform-quickstart/pull/6 addresses this

**Comment by dgkirkwood** [comment]
PR merged - closing.
