### ISSUE TITLE
The terraform tries to create the resource record set, but the instructions say to create the records ourselves?

### ISSUE THREAD

**Issue by GERey** [dgkirkwood/teleport-terraform-quickstart#4]
Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='georgetest.teleportdemo.com.', type='A'] but it already exists]

Is the error I get, and this is right because of these instructions

"A domain name which can be used for the public address of your server. This code assumes you have an existing hosted zone on AWS, and DNS records are created using that hosted zone. This proxy also uses Lets Encrypt for certificates, which requires a public DNS address." 

so I created those before hand, it doesn't seem like thats required though since it tries to create it for me?

**Comment by GERey** [comment]
https://github.com/dgkirkwood/teleport-terraform-quickstart/pull/7

**Comment by dgkirkwood** [comment]
Merged PR. Incoming change to the README to make things more clear.
